services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - PORT=8000
      - CORS_ORIGIN=http://localhost:5173
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - chat-app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_SERVER_API: /api/v1
        VITE_SOCKET_URL: http://localhost:8000
        VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID}
    ports:
      - "5173:80"
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
    networks:
      - chat-app-network

networks:
  chat-app-network:
    driver: bridge
